package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/naipi11/helix_copilot/internal/config"
	"github.com/naipi11/helix_copilot/internal/login"
	"github.com/naipi11/helix_copilot/internal/lsp"
)

var stdout io.Writer = os.Stdout
var stderr io.Writer = os.Stderr

func main() {
	os.Exit(run(os.Args[1:]))
}

func run(args []string) int {
	if len(args) == 0 || args[0] == "help" || args[0] == "--help" || args[0] == "-h" {
		printUsage()
		return 0
	}

	switch args[0] {
	case "model":
		return runModel(args[1:])
	case "configure-helix":
		return runConfigureHelix(args[1:])
	case "lsp":
		return runLSP(args[1:])
	case "login":
		if err := login.Run(login.DefaultRunner()); err != nil {
			fmt.Fprintf(stderr, "login failed: %v\n", err)
			return 1
		}
		return 0
	default:
		fmt.Fprintf(stderr, "unknown command: %s\n", args[0])
		printUsage()
		return 2
	}
}

func printUsage() {
	fmt.Fprintln(stdout, `helix-copilot - Copilot inline completion bridge for Helix

Commands:
  helix-copilot login                         start GitHub Copilot device login
  helix-copilot model <name> [--config path]  persist selected Copilot model
  helix-copilot configure-helix [--output p]  write Helix languages.toml snippet
  helix-copilot lsp                           run Copilot language server bridge`)
}

func runModel(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(stderr, "model name required")
		return 2
	}
	model := args[0]
	path := config.DefaultPath()
	for i := 1; i < len(args); i++ {
		if args[i] == "--config" && i+1 < len(args) {
			path = args[i+1]
			i++
		} else {
			fmt.Fprintf(stderr, "unknown model option: %s\n", args[i])
			return 2
		}
	}
	cfg, err := config.Load(path)
	if err != nil {
		fmt.Fprintf(stderr, "load config: %v\n", err)
		return 1
	}
	cfg.Model = model
	if err := config.Save(path, cfg); err != nil {
		fmt.Fprintf(stderr, "save config: %v\n", err)
		return 1
	}
	fmt.Fprintf(stdout, "model set to %s\n", model)
	return 0
}

func runConfigureHelix(args []string) int {
	out := filepath.Join(os.Getenv("HOME"), ".config", "helix", "languages.toml")
	for i := 0; i < len(args); i++ {
		if args[i] == "--output" && i+1 < len(args) {
			out = args[i+1]
			i++
		} else {
			fmt.Fprintf(stderr, "unknown configure option: %s\n", args[i])
			return 2
		}
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fmt.Fprintf(stderr, "create dir: %v\n", err)
		return 1
	}
	if err := os.WriteFile(out, []byte(helixSnippet()), 0o644); err != nil {
		fmt.Fprintf(stderr, "write snippet: %v\n", err)
		return 1
	}
	fmt.Fprintf(stdout, "wrote %s\n", out)
	return 0
}

func helixSnippet() string {
	return `# Generated by helix-copilot. Merge with your existing languages.toml if needed.
[language-server.copilot]
command = "helix-copilot"
args = ["lsp"]

# Python uses a fast local pylsp alongside Copilot. This keeps Helix's
# completion pipeline warm while Copilot starts, so ghost text triggers on the
# first few keystrokes. Style-only diagnostics are disabled to avoid warnings
# like W292 (missing final newline) while testing inline completion.
[language-server.pylsp.config.pylsp.plugins.pycodestyle]
enabled = false

[language-server.pylsp.config.pylsp.plugins.pyflakes]
enabled = false

[language-server.pylsp.config.pylsp.plugins.flake8]
enabled = false

[[language]]
name = "python"
language-servers = ["pylsp", "copilot"]

# Add "copilot" to each language where inline completion should be enabled, for example:
[[language]]
name = "go"
language-servers = ["gopls", "copilot"]
auto-format = true
`
}

func runLSP(args []string) int {
	if len(args) != 0 {
		fmt.Fprintf(stderr, "unknown lsp option: %s\n", strings.Join(args, " "))
		return 2
	}
	proxy := lsp.NewProxy()
	if err := proxy.Run(); err != nil {
		fmt.Fprintf(stderr, "copilot lsp proxy: %v\n", err)
		return 1
	}
	return 0
}

func runProxy(extra []string, subcommand string, more ...string) int {
	cmdArgs := append([]string{"--yes", config.DefaultLanguageServerPackage}, append([]string{subcommand}, more...)...)
	cmdArgs = append(cmdArgs, extra...)
	cmd := exec.Command("npx", cmdArgs...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(stderr, "run copilot language server: %v\n", err)
		return 1
	}
	return 0
}
